name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta una vez al día
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para guardar la imagen generada en el repositorio
    steps:
      - uses: lowlighter/metrics@latest
        with:
      # Token de GitHub integrado
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # Configuración para mostrar solo la tarjeta de lenguajes con barras horizontales
          template: classic
          base: ""
          filename: metrics-languages.svg
          plugins: languages
          plugin_languages_details: percentage
          plugin_languages_ignored: ""
          plugin_languages_limit: 8
