name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta una vez al día
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso obligatorio para que la acción pueda guardar el archivo
    steps:
      - uses: actions/checkout@v3

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: ""
          filename: metrics-languages.svg
          plugins: languages
          plugin_languages_details: percentage
          plugin_languages_ignored: ""
          plugin_languages_limit: 8

      # Este paso toma el SVG generado y lo guarda automáticamente en tu repositorio
      - name: Commit and push metrics-languages.svg
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: metrics-languages.svg
          commit_message: "Actualizar tarjeta de lenguajes de GitHub"
